### ISSUE TITLE
Separate ActionsCore module and put it on the Gallery?

### ISSUE THREAD

**Issue by TylerLeonhardt** [ebekker/pwsh-github-action-base#3]
It'd be cool to have a GitHub Toolkit module for PowerShell on the Gallery - yours is as close to the real thing as I could find.

**Comment by ebekker** [comment]
Are you saying to wrap up the functionality provided in the _optional support library_ (defined in the [ActionsCore.ps1](https://github.com/ebekker/pwsh-github-action-base/blob/master/lib/ActionsCore.ps1) script) as a Gallery-hosted module?

This can be done pretty easily (rename the script to a .psm1 and add a .psd1) and I would be happy to, but I originally thought packaging it up as an embedded script would make the GH Action operate a little quicker instead of having to import the module for each action invocation.  Perhaps the modularity is worth a little extra time?  It would also mean the Action code needs to install the module before any of it can make use of it.  Thoughts?

Or perhaps you meant something else?  What's throwing me off a little is the title mentions `ActionsCore` which implies my thought above, but in the description you say _Toolkit_ which perhaps means something more?

**Comment by TylerLeonhardt** [comment]
> Are you saying to wrap up the functionality provided in the optional support library (defined in the ActionsCore.ps1 script) as a Gallery-hosted module?

Yep! The reason I asked is because I own a couple templates:
https://github.com/TylerLeonhardt/container-action-pwsh
https://github.com/TylerLeonhardt/container-action-github-ops

And would love to include that module in those templates as well. Installing your module from the Gallery shouldn't impact perf _too_ much from my perspective and provides a nice way to handle versioning that module.

**Comment by ebekker** [comment]
As requested, you can pull in this [first version](https://www.powershellgallery.com/packages/GitHubActions/0.5.0.3) from the Gallery now.  Give it a try and let me know if there are any issues with it.

**Comment by ebekker** [comment]
The module is now in its [own dedicated](https://github.com/ebekker/pwsh-github-action-tools) repo, so please file any issues or feedback there.  Thanks.

**Comment by ebekker** [comment]
I'll update this template repo to make use of the module going forward, and will deprecate the embedded script file shortly.

**Comment by TylerLeonhardt** [comment]
exciting! I'll update my container templates :) - and also:

http://github.com/TylerLeonhardt/first-interaction-pwsh/

**Comment by ebekker** [comment]
The base project has been updated to show example of using the separate module.
